### ISSUE TITLE
Add auto release workflow + config to workflows repo so it gets propagated

### ISSUE THREAD

**Issue by surchs** [neurobagel/workflows#43]
We need to update `sync.yml` to push, to all repos that we want to auto-release:
- [x] bagel-cli release workflow (with PAT): https://github.com/neurobagel/bagel-cli/blob/main/.github/workflows/release.yaml
- [x] `.autorc` config file used by `auto` to these repos, following this template: https://github.com/BetaHuhn/repo-file-sync-action?tab=readme-ov-file#sync-the-same-files-to-multiple-repositories

**Comment by surchs** [comment]
Blocked until we do #44, so we don't have to make extra PRs when we do

**Comment by alyssadai** [comment]
Hey @surchs, I ended up pushing to your branch the `.autorc` file (and rejigged the sync configuration a bit) so that the files needed for automatically creating a GH release are all propagated as part of 
- https://github.com/neurobagel/workflows/pull/42

I think the rest of https://github.com/neurobagel/workflows/issues/44 might make sense to address separately (not as part of the deploy on release milestone) since it sounds like from the issue description there might be non-release-related workflow files we want to sync.
